### ISSUE TITLE
Create DB with tables “Talents”, “ TalentInfo” / test connection with DB

### ISSUE THREAD

**Issue by IlliaKyselov1902** [Vladyslav-Team/backend#10]
**Task is for User story:** [#3](https://github.com/Vladyslav-Team/frontend/issues/3)

**Creating a schema for database tables. Create the Talent and TalentInfo tables.**

**TODO:**

_Talent table:_

- [x]  PK Long id NN

- [x]  text e-mail NN

- [x]  text password NN

- [x]  name NN
 
- [x]  surname NN

_TalentInfo table:_

- [x] PK Long talent_id 1 to1 relation

- [x] text image

- [x] text experience (temporary solution, can be changed)

- [x] text location

- [x] text phone

- [x] LocalDateTime age (return INTEGER age to frontend)

- [x] text education

- [x] text about me

**Create inside the code:** 

- [x] connection between code and DB in the entity classes Talent, TalentInfo.

- [x] create queries in the interfaces TalentRepository, TalentInfoRepository

- [x] initialize the data.sql file with prepared inserts with talent and talentInfo.

- [x] config the application.properties to work with DB.

**Optional:**

- [x] Create Junit test to test the connection beetween DB and java code
