### ISSUE TITLE
Add the ability to delete the talent's account by sending the post mapping

### ISSUE THREAD

**Issue by SEM24** [Vladyslav-Team/backend#13]
**Task for UserStory: [22](https://github.com/Vladyslav-Team/frontend/issues/22)**

**TODO**

- [x] Write logic in service which deletes talent, depending on given parameter from controller.

- [x] Write GetMapping() which gets request body/request param with our talent.

- [x] Handle th exception in case the talent isn't exists.

**Comment by SEM24** [comment]
Endpoint:

DELETE:
http://localhost:28852/talents/1
