### ISSUE TITLE
Create endpoints for the tasks that interacts with viewing the information

### ISSUE THREAD

**Issue by SEM24** [Vladyslav-Team/backend#14]
**TODO**

Create texted version of the endpoints from mentioned tasks to prevent problems between frontend/backend and add them to current task in descriptions, review the json format from backed to frontend:

- [x] [12](https://github.com/Vladyslav-Team/backend/issues/12) Pagination

- [x] [6](https://github.com/Vladyslav-Team/backend/issues/6) View the talent's profile(view, update, delete)

- [x] [7](https://github.com/Vladyslav-Team/backend/issues/7) Register/Login the talent

- [x] [4](https://github.com/Vladyslav-Team/backend/issues/4) View the talents without pagination.
