### ISSUE TITLE
2.5. As a Guest, I want to be able to see the list of 'Proofs' with general information to check possible evidence of someone's proficiency.

### ISSUE THREAD

**Issue by PanfiDen** [Vladyslav-Team/backend#22]
- There is a list of Proofs which are displayed in form of text.

- Proofs have the status “Published”.

- Proof contains such general information as:

    - date of creation;

    - name of the Proof;
    
    - description.

- Updating Proofs list by Update buttom.

- The Proof list can be sorted by date of creation:

    - from new to old;

    - from old to new.

- By default Proofs displayed from new to old. 

**Tasks:**

frontend:

- [ ] [2.5.1 Сreate Pagination for Proofs Page](https://github.com/Vladyslav-Team/frontend/issues/84);
- [ ] [2.5.2 Create Proofs Page layout](https://github.com/Vladyslav-Team/frontend/issues/82).
- [ ] [2.5.3 Create Update button on Proofs Page](https://github.com/Vladyslav-Team/frontend/issues/83)
- [ ] [2.5.4 Add sort function on Proofs Page](https://github.com/Vladyslav-Team/frontend/issues/85)

backend:

- [x] [2.5. Add the ability to display Proofs on the main page (with sort)](https://github.com/Vladyslav-Team/backend/issues/28);
- [x] [2.5. Create table “Proof”/ test connection with DB](https://github.com/Vladyslav-Team/backend/issues/29).
