### ISSUE TITLE
2.1. As a Talent, I want to be able to see the list of my Proofs on my Profile page.

### ISSUE THREAD

**Issue by PanfiDen** [Vladyslav-Team/backend#23]
- Talent can see a list of its own Proofs in its own Talent’s profile.

- Proof has one of the statuses: Draft, Hidden, Published.

- Proof contains such information as:

    - date of creation (dd.mm.yyyy);

    - name of the proof;

    - description

- Proofs displayed from new to old.

**Tasks:**

frontend:
- [x] [2.1.1 Create Proofs Component](https://github.com/Vladyslav-Team/frontend/issues/67)
- [x] [2.1.2 Create list of Proofs on Profile Page](https://github.com/Vladyslav-Team/frontend/issues/81)

backend:

- [x] [2.1(2.6). Add the ability to view your Proofs and Proofs of other Talents on the profile page](https://github.com/Vladyslav-Team/backend/issues/30)
