### ISSUE TITLE
2.2. As a Talent, I'd like to add a new Proofs in my Profile page.

### ISSUE THREAD

**Issue by PanfiDen** [Vladyslav-Team/backend#25]
- There is a function to Add new Proofs on a Profile page of a Talent.

    - During the addition process Talent must fill in the fields specified in the US-2.1:

        - name of the proof;

        - description.

    - For each field in Add Proofs function is performed data validation.

    - There must be a button to Save the Proof after filling in the fields.

    - If Talent closes the Proof without saving, changes won’t be applied

    - When adding a new Proof - assigned “Draft” status. Only the creator is allowed to view the Proof with that status.

    - After adding, the Proof appears on the Profile page.

- The Proofs appear on the Profile page with status “Draft”

- There must be a button to Publish the Proof. 

    - If click the “Publish“ button when a Proof has “Draft“ status, the confirming notification appears (“If you publish the Proof, you won’t be able to edit it anymore. Publish it?“)

    - If click the “Publish“ button when a Proof has “Hidden“ status, the confirming notification appears(“If you publish the Proof, everyone will see it. Publish it?“)

    - If Talent confirmed publishing, change the Proof status from “Draft” to “Published” or from “Hidden” to “Published”

- There must be a button to Hide the Proof

    - If click the “Hide“ button when a Proof has “Draft“ status, a pop-up notification appears (“After hiding your Proof you won’t be able to edit it. Hide it?“)

    - When clicking the “Hide“ button, the Proof changes its status to “Hidden”

    - Proof with “Hidden“ status is visible only to the creator.

Tasks:

frontend:

- [x] [2.2.1 Create Proof with status Draft](https://github.com/Vladyslav-Team/frontend/issues/88).
- [x] [2.2.2 Create Edit proof Page](https://github.com/Vladyslav-Team/frontend/issues/87)
- [x] [2.2.3 Create Proof with status Published + confirm alert](https://github.com/Vladyslav-Team/frontend/issues/89)
- [x] [2.2.4 Create Proof with status Hiden + confirm alert](https://github.com/Vladyslav-Team/frontend/issues/90)

backend:

- [x] [2.2. Add the ability to add Proof to your profile](https://github.com/Vladyslav-Team/backend/issues/31)
