### ISSUE TITLE
2.3. As a Talent, I'd like to edit my Proofs to update information.

### ISSUE THREAD

**Issue by PanfiDen** [Vladyslav-Team/backend#26]
- There is a function to edit the Proofs on Talent’s Profile page.

- Proof editing is allowed only if Proof has “Draft” status.

- The ability to edit such fields as indicated in US-2.2

- Possibility to save edited data by pressing the "Save" button.

- Ability to exit Edit mode without saving.

- Talent can change the statuses from “Draft” to “Hidden” or “Draft” to “Published” when editing is finished. Reverse changing is impossible.

- After pressing the “Published” or “ the “Hidden” buttoms data is saving and Proof appear on the Profile page.

- Perform validation for input data for each field in editing mode

Tasks:

frontend:
- [x] [2.3.1 Create Edit proof button](https://github.com/Vladyslav-Team/frontend/issues/91).

backend:

- [x] [2.3 Add the ability to edit fields and save or delete changes only your Proofs with status DRAFT](https://github.com/Vladyslav-Team/backend/issues/88)
- [x] [2.3. Add the ability to change the status of Proof: Draft to Published](https://github.com/Vladyslav-Team/backend/issues/33)
- [x] [2.3. Add the ability to change the status of Proof: from Published to Hidden](https://github.com/Vladyslav-Team/backend/issues/34)
