### ISSUE TITLE
Add the ability to display talents on the main page (no pagination)

### ISSUE THREAD

**Issue by IlliaKyselov1902** [Vladyslav-Team/backend#4]
**Task is for User story:** [#3](https://github.com/Vladyslav-Team/frontend/issues/3)

**Implementation of business logic :**

- [x] write methods in the controllers TalentController, TalentInfoController and call the business logic for displaying all talents.

- [x] write the business logic in the TalentServiceImpl and TalentInfoServiceImpl.

- [x] return data(json) about talent with the showAllTalents method in service class to controller with:

- id
- image
- name
- surname
- location
- experience

Import the service into the controller and add autowired if neccessary

**Create a Method**

**GetMapping("/talents")** to display talent, hadle exception.

**Comment by SEM24** [comment]
Structure of task #4 (json body)

  {
    "id": 1,
    "image": "staticImage.png",
    "name": "Samer",
    "surname": "Khomsi",
    "location": "Kharkiv"
  }
