### ISSUE TITLE
Add exception handlers to prevent errors in services (business logic)

### ISSUE THREAD

**Issue by IlliaKyselov1902** [Vladyslav-Team/backend#5]
To complete this task you need to implement a variety of error handlers.

**TODO**

- [x] TalentNotFoundException       404 status code

- [x] ForbiddenRequestException    403 status code 

- [x] EntityAlreadyExistException     409 status code

- [x] UnauthorizedUserException    401 status code

**Optionally**: create class marked with @ControllerAdvice which contains handlers

**Comment by IlliaKyselov1902** [comment]
Add UnauthorizedUserException

**Comment by vlad-khrychov** [comment]
Add {id} in TalentNotFoundException
Talent with {email} AlreadyExistException
