### ISSUE TITLE
Add ability to view all talent information(profile)

### ISSUE THREAD

**Issue by IlliaKyselov1902** [Vladyslav-Team/backend#6]
**Task is for User story:** [#14](https://github.com/Vladyslav-Team/frontend/issues/14)

To complete this task you should get extended information about user from database, and return it

**TODO:**

- [x] create new method in service and write a business logic to handle a talent profile

- [x] create a new rest method and handle @GetMethod(".../profile")

- [x] add new query in repository to get the talent profile
