### ISSUE TITLE
Build the start project with all dependencies

### ISSUE THREAD

**Issue by IlliaKyselov1902** [Vladyslav-Team/backend#9]
**Task for UserStory:** [#3](https://github.com/Vladyslav-Team/frontend/issues/3)

Building the project with all dependencies and packages.

**TODO:**

- [x] packages for talent and talentInfo

- [x] the entity classes Talent, TalentInfo

- [x] interface TalentRepository, TalentInfoRepository

- [x] MainController, TalentController

- [x] TalentServiceImpl, interface TalentService
